on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrworkflow1674181911184.azurecr.io
        username: ${{ secrets.acr_acrworkflow1674181911184_username }}
        password: ${{ secrets.acr_acrworkflow1674181911184_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrworkflow1674181911184.azurecr.io/exampleaks1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrworkflow1674181911184.azurecr.io/exampleaks1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_exampleaks1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep example-aks1abf1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace example-aks1abf1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: example-aks1abf1
        container-registry-url: acrworkflow1674181911184.azurecr.io
        container-registry-username: ${{ secrets.acr_acrworkflow1674181911184_username }}
        container-registry-password: ${{ secrets.acr_acrworkflow1674181911184_password }}
        secret-name: exampleaks1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: example-aks1abf1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrworkflow1674181911184.azurecr.io/exampleaks1:${{ github.sha }}
        imagepullsecrets: |
          exampleaks1dockerauth
